name: magentra
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pywin32  # Critical for Windows compatibility
  - pip:
    - langchain==0.3.18
    - langchain-openai==0.3.4
    - fastapi==0.115.8
    - uvicorn==0.34.0
    - python-dotenv==1.0.1
    - pytest==8.3.4
    - supabase==2.13.0
    - neo4j==5.28.0
    - langchain-community==0.3.17
    - langchain-core==0.3.34
    - tiktoken==0.8.0
    - setuptools==69.5.1
    - aiohttp>=3.9
    - numpy>=1.26
    - pydantic>=2.7
    - python-multipart  # Required for FastAPI form handling 